// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataTableServerSide_GenericSortNdSearchMethod.DbContextFile;
using DataTableServerSide_GenericSortNdSearchMethod.Enities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DataTableServerSide_GenericSortNdSearchMethod.DbContextFile.Configurations
{
    public partial class EmployeeTableConfiguration : IEntityTypeConfiguration<EmployeeTable>
    {
        public void Configure(EntityTypeBuilder<EmployeeTable> entity)
        {
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.Department).HasMaxLength(50);

            entity.Property(e => e.EmailId).HasMaxLength(50);

            entity.Property(e => e.FirstName).HasMaxLength(50);

            entity.Property(e => e.LastName).HasMaxLength(50);

            entity.Property(e => e.Mobile).HasMaxLength(50);

            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EmployeeTable> entity);
    }
}
