// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataTableServerSide_GenericSortNdSearchMethod.DbContextFile.Configurations;
using DataTableServerSide_GenericSortNdSearchMethod.Enities;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace DataTableServerSide_GenericSortNdSearchMethod.DbContextFile
{
    public partial class DatatabelexampledbContext : DbContext
    {
        public DatatabelexampledbContext()
        {
        }

        public DatatabelexampledbContext(DbContextOptions<DatatabelexampledbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<EmployeeTable> EmployeeTable { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.EmployeeTableConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
